AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for ASG DNS Management

Parameters:
    InstanceType:
      Type: String
      Default: t2.micro
    ImageId:
      Type: String
      Default: ami-e8702dff
    KeyName:
      Type: String
      Default: master
    VpcId:
      Type: String
      Default: vpc-5d777b38
    PublicSubnetList:
      Type: CommaDelimitedList
      Default: subnet-d7e7eaed,subnet-7d78e356,subnet-7d78e356,subnet-7d78e356
    LambdaFunctionName:
      Type: String
      Default: AutoScalingDNSManager


Resources:
  AutoScalingGroupSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: 'AutoScalingDNSManagerSNS'

  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        Ref: PublicSubnetList
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: LaunchConfiguration
      MinSize: 1
      MaxSize: 3
      NotificationConfigurations:
        - TopicARN:
            Ref: AutoScalingGroupSNSTopic

          NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_TERMINATE

  LaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      AssociatePublicIpAddress: True
      ImageId:
        Ref: 'ImageId'
      InstanceType:
        Ref: 'InstanceType'
      KeyName:
        Ref: KeyName
      SecurityGroups:
        - Ref: WebServerSecurityGroup


  LambaFunctionEventListener:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName:
        Fn::Join:
          - ':'
          -
            - arn:aws:lambda
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - function
            - Ref: LambdaFunctionName
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: AutoScalingGroupSNSTopic

  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Inbound HTTP Rule
      SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '80'
              ToPort: '80'
              CidrIp: 0.0.0.0/0
      VpcId:
        Ref: VpcId

