AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function to deal with DNS Updates for ASGs

Parameters:
  LambdaFunctionName:
    Type: String
    Default: AutoScalingDNSManager
  S3Bucket:
    Type: String
    Default: lamba-dnsmanager
  S3BucketKey:
    Type: String
    Default: code-v1.zip

Resources:
  DNSManagerLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          Ref: S3Bucket
        S3Key:
          Ref: S3BucketKey
      Description: Lambda Function to manage DNS entries for autoscaling events
      FunctionName: AutoScalingDNSManager
      Handler: autoscalingDNSManager.main
      MemorySize: 512
      Runtime: python2.7
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      # High timeout to allow for function to deal with extended instance spin up times.
      Timeout: 300

  LambdaIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  LambdaIAMRolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              # Read Only EC2 Access
              - 'ec2:Describe*'
              # Full Logs/S3/Route53 Access - Should be more restrictive but for POC this will suffice
              - 'logs:*'
              - 's3:*'
              - 'route53:*'
            Resource: '*'
      Roles:
        -
          Ref: LambdaIAMRole

#  LambdaIAMProfile:
#    Type: 'AWS::IAM::InstanceProfile'
#    Properties:
#      Path: /
#      Roles:
#        -
#          Ref: LambdaIAMRole



